### ISSUE TITLE
Unclear what to do if neither compatibility tab is visible nor outlook is installed

### ISSUE THREAD

**Issue by adrianjellis** [MicrosoftDocs/OfficeDocs-Support#1002]
The page doesn't describe what to do when:
- Compatibility tab isn't visible, and
- Outlook is not installed

In particular, it does not provide guidance on whether to follow the instructions in the error message i.e. " You should repair the Office program by using Control Panel."

I was unable to get the compatibility tab to appear by amending the registry key - apparently by design. I tried a Quick Repair which failed. Tried an Online Repair which prompted for the activation key. At this point it became clear that the issue is likely due to the fact that the key was originally activated using a different MS account (which my client doesn't have access to). Online activation fails and telephone activation not available. I just hope my client doesn't lose access to their office suite as a result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dfca234-859d-b43d-5868-a61f709b1947
* Version Independent ID: 794772a8-2dd5-9ff3-ccd0-4c22e06e144d
* Content: [Cannot verify the license for this product when start an Office app - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/license-issue-when-start-office-application)
* Content Source: [Office/Client/activation/license-issue-when-start-office-application.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation/license-issue-when-start-office-application.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@adrianjellis The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
