### ISSUE TITLE
Needs clarification

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-Support#1031]
Document says it also applies to Project Server, but all instructions in resolution refer to Project Online (for example, log into tenant, etc.). Please correct so the resolution instructions are applicable to the products indicated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc5543b-4cea-7daa-fc2e-ba183f2e9ec0
* Version Independent ID: 8c0e79a1-fdd6-a1b2-1651-956db18905b0
* Content: [You receive an error when accessing Project Web App - Office](https://docs.microsoft.com/en-us/office/troubleshoot/project/error-when-access-pwa)
* Content Source: [Office/Client/project/error-when-access-pwa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/project/error-when-access-pwa.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
This is by design for Project Online (and Project Server 2013) regardless of the permissions mode on the PWA site so I don’t think there is much value in changing the document.  The steps are more specific to Project Online but the user of server would be able to understand what they need to do to resolve the same issue.
