### ISSUE TITLE
New-Remotemailbox does not have a -Shared parameter

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Support#104]
The command example under "Alternative method" won't work as there is no -shared parameter for New-Remotemailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a447737-4483-7fc5-afc7-ca47952af9f8
* Version Independent ID: 3e476557-6ba6-c668-1784-2b7a73f6d6f2
* Content: [Users in a hybrid deployment can't access a shared mailbox in Exchange Online - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/shared-mailboxes/cannot-access-mailbox)
* Content Source: [Exchange/ExchangeHybrid/shared-mailboxes/cannot-access-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/shared-mailboxes/cannot-access-mailbox.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello, it was added in Exchange Server 2016 CU10 (https://docs.microsoft.com/en-us/powershell/module/exchange/new-remotemailbox?view=exchange-ps)
Thank you

**Comment by nam31** [comment]
@Canis-Lupis Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
