### ISSUE TITLE
Link a table in Access in which there is a column name with a period

### ISSUE THREAD

**Issue by guilhermesurek** [MicrosoftDocs/OfficeDocs-Support#1047]
Hello. Is there any way to link a SQL Server table to Access, in which there is a column name with a period?
I can't change anything in the SQL Server. I'm using ODBC connection and Access 2016.

![image](https://user-images.githubusercontent.com/23281984/105707947-7a301480-5ef2-11eb-86da-54b3c85708f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57867ef2-45c0-27af-443d-45cef93b0af6
* Version Independent ID: 05956bd0-b66f-1728-d7f3-4af5ac43e8eb
* Content: [Errors using special characters in Access databases - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/error-using-special-characters)
* Content Source: [Office/Client/access/error-using-special-characters.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/error-using-special-characters.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by MaryQiu1987** [comment]
This issue is not related to the article, you can read the following reference articles:

https://docs.microsoft.com/en-us/office/troubleshoot/access/create-dsn-less-connection-linkted-table
https://support.microsoft.com/en-us/office/import-or-link-to-data-in-an-sql-server-database-a5a3b4eb-57b9-45a0-b732-77bc6089b84e
