### ISSUE TITLE
Did the OOF settings change in Exchange Online?

### ISSUE THREAD

**Issue by NavishkarSadheo** [MicrosoftDocs/OfficeDocs-Support#1063]
Hi

Did the OOF settings change to only send one OOF message to the sender? 

I remember before that a sender would receive one OOF message for every message sent to the mailbox that had OOF enabled.

Just curious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ae1273-fbb6-ff3f-f1df-df81508f6d6b
* Version Independent ID: 1e012785-3724-77c2-d2d0-4a5942ea4fbc
* Content: [Understanding and troubleshooting Out of Office (OOF) replies - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/understand-troubleshoot-oof-replies?source=docs)
* Content Source: [Exchange/ExchangeOnline/email-delivery/understand-troubleshoot-oof-replies.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/email-delivery/understand-troubleshoot-oof-replies.md)
* Product: **office 365**
* GitHub Login: @TobyTu
* Microsoft Alias: **damande**

**Comment by msbemba** [comment]
@NavishkarSadheo Thank you for your feedback. You are correct. The Out of Office Assistant sends an automatic reply to notify users who send you messages that you are away from the office. Your reply is only sent once to a message sender. The count is reset when you toggle the Out of Office Assistant. Microsoft Exchange clears its internal "sent to" list when you disable the Out of Office Assistant.

If you would like to have a reply sent for every message, use Rules instead of the Out of Office Assistant.

Hope this helps!

@nam31 There are no changes required in this document.

Thanks
Sri
