### ISSUE TITLE
OutlookSearchRepair is not supported on the recent MacOS X Version

### ISSUE THREAD

**Issue by SebastianWalter1999** [MicrosoftDocs/OfficeDocs-Support#109]
Hey there!

I have got a problem with the "OutlookSearchRepair" for MacOS X. When I try executing the App there is an error message that says that this version of macOS is not supported. 

![Bildschirmfoto 2019-09-04 um 13 06 50](https://user-images.githubusercontent.com/54892423/64250242-eb45e500-cf15-11e9-9428-6fa1ba6ad873.png)

To be sure I tried it on two different MacBooks, a 2013 and a 2017. 
**MacOS X Version:** 10.14.6
**Tested MacBooks:** MacBook Pro 2013 and MacBook Pro 2017. 
I would really appreciate some help, because we got some problems with the Outlook Search on some Macs.

Best regards

**Comment by nam31** [comment]
@SebastianWalter1999 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by SebastianWalter1999** [comment]
@nam31 At the time I created the issue, this repository was referenced on the corresponding Microsoft support page ([https://docs.microsoft.com/de-de/outlook/troubleshoot/outlook-for-mac/useful-tools](https://docs.microsoft.com/de-de/outlook/troubleshoot/outlook-for-mac/useful-tools)) The associated page in this repository is this: https://docs.microsoft.com/de-de/outlook/troubleshoot/outlook-for-mac/useful-tools  [https://docs.microsoft.com/de-de/outlook/troubleshoot/outlook-for-mac/useful-tools](https://docs.microsoft.com/de-de/outlook/troubleshoot/outlook-for-mac/useful-tools)

**Comment by msbemba** [comment]
@SebastianWalter1999 Thank you for your feedback. You are correct, Due to some changes in macOS Mojave, this tool no longer works in 10.14 and higher.  As mentioned in the note, in your case you can follow the steps below to reindex Spotlight for Outlook for Mac.

Choose Apple menu, then System Preferences, and then Spotlight.

Select the Privacy tab.

In Finder:

On the Go menu, select Go to Folder...

Copy and paste the following location into the "Go to the folder:" dialog box and select Go:

~/Library/Group Containers/UBF8T346G9.Office/Outlook/Outlook 15 Profiles/

Drag the "Main Profile" folder to the Privacy tab. Once added, remove the folder from the Privacy tab, and Spotlight will re-index the folder.

You must perform this step for any additional profile folders you have.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@SebastianWalter1999 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
