### ISSUE TITLE
ReportToOriginatorEnabled for Unified Groups?

### ISSUE THREAD

**Issue by mvanders** [MicrosoftDocs/OfficeDocs-Support#1094]
Based on https://docs.microsoft.com/en-us/exchange/troubleshoot/email-delivery/external-recipients-not-receiving-distribution-group-emails, I was wondering if there is also this options available for an O365 group (Unified Group)  which also has a mailbox and which we use a lot to send mail to!

**Comment by mvanders** [comment]
Why is this not being picked up by anyone?

**Comment by msbemba** [comment]
@mvanders Thank you for your feedback. Sorry about the delay in picking up this issue. 

Yes, ReportToOriginatorEnabled is available for unified groups, You would use the set-unfiedgroup cmdlet instead of set-distributiongroup  to modify value on an M365 group


Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@mvanders Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
