### ISSUE TITLE
Update "Applies to" section

### ISSUE THREAD

**Issue by anoopras4** [MicrosoftDocs/OfficeDocs-Support#1108]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fcbe622-fa9d-15c0-038b-259418a6c0ec
* Version Independent ID: 123ff403-baaa-d4e6-f7a5-defbebe827b4
* Content: [Request approval failed when you process a pending request - SharePoint](https://docs.microsoft.com/en-US/sharepoint/troubleshoot/sharing-and-permissions/request-approval-failed)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/request-approval-failed.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by anoopras4** [comment]
Currently it suggests as below
Applies to: SharePoint Online

But its applicable to SharePoint On Prem versions as well like SharePoint 201, SharePoint 2016 and SharePoint 2019.

Is it possible to update it?

**Comment by VLG17** [comment]
@anoopras4 The article has been updated and is showing both online and on-premises versions under _Applies to:_

**Comment by nam31** [comment]
@anoopras4 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
