### ISSUE TITLE
What the heck does any of this mean and how is it supposed to help me?

### ISSUE THREAD

**Issue by tommalia** [MicrosoftDocs/OfficeDocs-Support#1112]
I'm sorry I can't be more clear in my question, and subsequently my question is probably as cryptic to you as your "answers" are to me....
I DO NOT understanding all this talk about "personal" versus "organizational" accounts or "tenants" or anything else.  My "organization" is not some large corporation like your "Cosco.com" example, It is MY small company that I own the domain name for.  
I'm just at a complete lose to begin to know how to make sense of Microsoft's identification system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab509e31-52d3-be39-501a-aef6c701201c
* Version Independent ID: 4c2f3f40-91ca-7bb2-3090-6fd38ba82f40
* Content: [Someone has already set up Teams for your organization error in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/someone-has-already-setup-teams)
* Content Source: [Teams/teams-sign-in/someone-has-already-setup-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/someone-has-already-setup-teams.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @TobyTu
* Microsoft Alias: **billkau**

**Comment by VLG17** [comment]
@tommalia The article talks about 3 potential causes. Did you manage to understand which one applies to the issue you are encountering?

Could you please share some details about how we could improve this article so that it would be more clear? 

Maybe adding some links for the terms that you mentioned (personal and organizational account, tenants), which are not that clear? Like:

https://techcommunity.microsoft.com/t5/itops-talk-blog/what-s-the-difference-between-a-personal-microsoft-account-and-a/ba-p/2241897

**Comment by VLG17** [comment]
@tommalia Looking forward to your feedback here so we understand how we can proceed.

**Comment by nam31** [comment]
@tommalia We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you
