### ISSUE TITLE
What attachment types specifically does this target?

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/OfficeDocs-Support#1125]
This sounds quite handy, but "block attachments with executable content" needs more detail.
I think we can assume it'll pick up a .exe file, but what about, for example, some vbscript embedded within a .chm?
Javascript within a PDF? Anything in a .zip? What if the .exe is renamed to .txt?
See what I mean? If i really want to secure my organisation, I need to know exactly what i've chosen to block so that anything that's not covered by "executable content" in this rule can be picked up separated by another rule - if necessary.
How does this actually work and what does it specifically target?
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dca0652-8a01-1a96-fa99-0fd68ccaad13
* Version Independent ID: 9a1baad1-bfaf-d931-c95f-02a659a3c253
* Content: [Reduce malware threats via file attachment blocking - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam-and-protection/how-to-reduce-malware-threats-via-file-attachment-blocking)
* Content Source: [Exchange/ExchangeOnline/antispam-and-protection/how-to-reduce-malware-threats-via-file-attachment-blocking.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam-and-protection/how-to-reduce-malware-threats-via-file-attachment-blocking.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@rcmpgi Thank you for your feedback. The system automatically detects file types by inspecting file properties rather than the actual file name extension, thus helping to prevent malicious hackers from being able to bypass mail flow rule filtering by renaming a file extension. I have added this information to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1379

You can also visit https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments which talks in detail about how to use mail flow rules to inspect message attachments in Exchange Online.

Thanks
Sri

**Comment by nam31** [comment]
Closing via #1379
Thank you
