### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by xshiiiidev** [MicrosoftDocs/OfficeDocs-Support#1136]
On this page tutorial https://docs.microsoft.com/en-us/office365/troubleshoot/licensing/determine-office-license-type?tabs=windows

There is an type error on this part

`At the command prompt, type cscript OSPP.VBS” /dstatus`

it is supposed to be

`At the command prompt, type cscript OSPP.VBS /dstatus`

**Comment by VLG17** [comment]
@xshiiiidev The article has been updated and does not contain the extra "

**Comment by nam31** [comment]
@xshiiiidev Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
