### ISSUE TITLE
Error with Office forms-based authentication and certain OAuth providers

### ISSUE THREAD

**Issue by cbrianball** [MicrosoftDocs/OfficeDocs-Support#1144]
I am experiencing an issue similar to the one described in https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/authentication/not-render-a-custom-duo-api-multi-factor-authentication-login-page.md

In this case, I have a custom app that causes Office to use MS-OFBA and authenticate. It works great for Azure AD, but I tried to authenticate with Google, and I get the error. There are iframes on the Google page (though, from what I can tell the iframes are loading https pages) -- but for all I know, they may start without a "src" attribute.

I'm hoping since Google is a very common OAuth provider that you all have a way around this issue.

**Comment by msbemba** [comment]
@cbrianball Thank you for your feedback. Do you get the error "Your organization's policies are preventing us from completing this action for you " ?  I could not replicate this in our lab, I understand the issue could be unique. Let us know if this is still an issue and if there is an update required in the document.

Thanks
Sri

**Comment by cbrianball** [comment]
@msbemba Thank you for taking the time to look at this.

Yes, I am getting the message you mentioned. I'm attaching a gif of what my experience is. I retried again today and I am getting the same error.

The "Select Provider" page is a page I have created for my website. Clicking on the "Google" button does a postback to my webpage, the response of the postback is a 302 redirect to `https://accounts.google.com/o/oauth2/v2/auth?...`.

![repro](https://user-images.githubusercontent.com/640035/123101906-7f8e7e00-d402-11eb-9c3f-178464c74653.gif)

The last website I can see before I get the error is accounts.google.com.

I'm not 100% sure that iframes are the issue, but I recall testing this a few months ago and it definitely seemed plausible.

The two iframes I see when I navigate to accounts.google.com have `src` values of:
- `https://accounts.youtube.com/accounts/CheckConnection?....`
- `https://accounts.google.com/_/bscframe`

**Comment by msbemba** [comment]
@cbrianball Thank you for the update. I don't think this is an issue with Iframe. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Based on your interaction with support, let us know if you would like us to modify the document.

Thanks
Sri
