### ISSUE TITLE
Known Teams issue MC230715 is missing

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-Support#1213]
Info on this issue open since last year is not represented on this page of known issues for Teams

https://techcommunity.microsoft.com/t5/microsoft-teams/email-notifications-for-personal-mentions/m-p/1044937

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f57501e-bafa-eeeb-ea6c-7126182f1e0a
* Version Independent ID: eb9112dd-3ce2-23dd-fad4-4caa2d85ad47
* Content: [Information about Teams known issues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-welcome)
* Content Source: [Teams/teams-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-welcome.md)
* Service: **msteams**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @ssmiller60, thank you for your feedback.

I've tested it, and it seems to be working now. I get the email for a personal mention in a Teams channel.

**Comment by dariomws** [comment]
Please test it again and let me know if it still fails. Thanks!

**Comment by nam31** [comment]
@ssmiller60 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
