### ISSUE TITLE
Microsoft Support and Recovery Assistant

### ISSUE THREAD

**Issue by yirmio** [MicrosoftDocs/OfficeDocs-Support#1229]
Hey

1. link to download Microsoft Support and Recovery Assistant is broken.
2. how can i use Microsoft Support and Recovery Assistant to automatically run all scripts?

Thanks!
Yirmi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1375a9d-fa30-75a2-5aea-daca0e74f142
* Version Independent ID: c9510807-f261-5a24-0039-d6bf5ad630e5
* Content: [Reset Microsoft 365 Apps for enterprise activation state - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state)
* Content Source: [Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md)
* Service: **o365-solutions**
* GitHub Login: @MJP-MSFT
* Microsoft Alias: **mattphil**

**Comment by msbemba** [comment]
@yirmio Thank you for your feedback.

1)The link automatically downloads the setup file for Support and Recovery Assistant. Let me know what happens when you access the link.
2) When you select Office and choose activation issues, it automatically runs the script in the backend

![image](https://user-images.githubusercontent.com/45987684/121140739-d4a19000-c857-11eb-8fb0-32acb70a882f.png)


Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yirmio Hopefully we answered your question. In case there are any changes required in the document, let us know.

Thanks
Sri

**Comment by nam31** [comment]
@yirmio Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
