### ISSUE TITLE
Not helping

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/OfficeDocs-Support#123]
We followed all the steps in this article, we have 500, around 60 of them are randomly complaining about this issue. any plans to fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Troubleshoot Excel opening blank when double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank#feedback)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
The comment does not have enough details so there is not much we can add. Current O365 has already resolved most of those issues by moving away from DDE to open workbooks (last year). Older editions of Excel could run into the DDE issues although reality is the issue is a problem in Windows with DDE and not Excel. Note that this article was written in collaboration with the PG so includes all of the known scenarios they had.

You may want to open a support case if you want to get further assistance in troubleshooting it.

**Comment by nalhemyariirexorg** [comment]
I'm not clear what details you're looking for. Windows 10 Pro 1809 (and 1903), Office 365 ProPlus latest version available today in monthly channel, I'm not sure what DDE and PG means, if there are other details you're looking for I'm happy to provide. My comments are to an article published to help users around the world or is it exclusive to certain audience?

**Comment by jlriesco** [comment]
This site is intended for a Commercial audience. For consumers, we have http://www.support.office.com 

DDE stands for _**Dynamic Data Exchange**_ (more info here: https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-dynamic-data-exchange)

PG means Product Group, the team who develops Office. Since this problems seems related more to Windows than Office, perhaps it will get resolved in the next Win 10 update.

I would recommend you to open a support case with a Microsoft Support Engineer to help you solve your problem.

I hope this helps.
