### ISSUE TITLE
Microsoft-Support-und Wiederherstellungs-Assistenten: Designfehler bei Authentifizierung 

### ISSUE THREAD

**Issue by ukr966** [MicrosoftDocs/OfficeDocs-Support#1240]
Wenn das "**SUPPORT**-Tool" unabhängig von der Software verwendeten Produktlizenz genutzt werden darf, dann muss auch keine Authentifizierung durchgeführt werden.

Zumindest muss gewährleistet sein, dass der auf der Supportseite 
[https://docs.microsoft.com/de-DE/outlook/troubleshoot/performance/how-to-scan-outlook-by-using-microsoft-support-and-recovery-assistant]
angegebene Workaround funktioniert.

Es darf nicht sein, dass die Nutzung eines Supporttools komplizierter ist als die Nutzung des Produktes.

**Comment by msbemba** [comment]
@ukr966 Thank you for your feedback. The support tool can be used irrespective of the license or office product in use. However, If you sign in to SaRA by using an account that is not in Office 365, there is no option to send your files to Microsoft.

Hope this answers your question.

Thanks
Sri

**Comment by nam31** [comment]
@ukr966 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
