### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/OfficeDocs-Support#1247]
How do you deploy this .potx file through Intune, specifically the policy for Office Apps
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6996d7bd-9a55-8bd6-1bb7-a3fd33e666ad
* Version Independent ID: 2cd87412-d518-fb75-d365-d654f3986579
* Content: [Set the default font for Office applications - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/set-default-font)
* Content Source: [Office/Client/office-suite-issues/set-default-font.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/set-default-font.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by VLG17** [comment]
@bballpaul4work You could deploy a simple .msi file as a [Line of Business App using Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-windows), thus copying the template to that location for all user profiles.

**Comment by nam31** [comment]
@bballpaul4work Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
