### ISSUE TITLE
Outlook - Send immediately after connect dont work (hook dont save)

### ISSUE THREAD

**Issue by wunderfliege** [MicrosoftDocs/OfficeDocs-Support#1295]
Hello.

I have this Problem: https://docs.microsoft.com/de-de/outlook/troubleshoot/synchronization/email-stays-in-outbox-until-manually-send-or-receive

I have exactly this problem. If I check “send immediately after connected” click on OK and send the mail. When i restart Outlook - the hook is gone again. If I set it again, save with ok, restart Outlook, the hook is gone again. How can I fix the problem that the hook stays in there permanently?

**Comment by msbemba** [comment]
@wunderfliege Thank you for your feedback. Usually, the settings stick together if you have your settings saved in the cloud. Navigate to options-->General-->Store my outlook settings in the cloud.

![image](https://user-images.githubusercontent.com/45987684/125065773-dcab5480-e0cf-11eb-88a1-53ef7062cd21.png)

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@wunderfliege Just circling back to check if you were able to fix the issue or if it still persists.

Thanks
Sri

**Comment by nam31** [comment]
@wunderfliege  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
