### ISSUE TITLE
Feedback on Original KB number: 2958272 (recently updated)

### ISSUE THREAD

**Issue by NeilAWalker** [MicrosoftDocs/OfficeDocs-Support#1303]
Please be more forthcoming and honest with the cause for this kind of issue.  The cause in the article is written: "The Save copies of messages in the Sent Items folder option in Outlook is disabled."  That wasn't the root cause.  I've been using Outlook for years - I've never had this issue before.  I almost never go to Options, and I certainly wouldn't update a setting like this.  The only explanation for a root cause appears to be that a routine update to the application has flipped this setting.  If it isn't that, something else has triggered its update and it needs to be found out exactly what did it.  Given the article has recently been updated, I suspect that you've had a flurry of users with the same problem.

The worst thing about the fault is that it is silent - there was no cue that it had changed until I went to find an email I needed to forward to someone.  Luckily it was only a matter of hours in my case and I wasn't missing too many emails. Those I was missing I managed to recover by getting a colleague to send them back to me - but that wouldn't always be possible.  In my business, not having copies of emails as an audit trail is bad news.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1d82c1-752e-e85a-30ca-bba94f138d7c
* Version Independent ID: f92bb03b-c526-7d98-55b4-f3b212666e68
* Content: [Emails are not saved to Sent Items - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/email-management/email-sent-are-not-saved-to-sent-items-folder)
* Content Source: [Outlook/Client/email-management/email-sent-are-not-saved-to-sent-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/email-management/email-sent-are-not-saved-to-sent-items-folder.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by AurelianoLobato** [comment]
Boa tarde,
Resolvi o problema reparando o Office, mas apenas para emails novos, emails que já haviam sido enviados, não consegui encontrar.
Office 2016 Plus

**Comment by MaratMussabekov** [comment]
Hello @NeilAWalker ,
The reasons for the issues may vary, some may be caused by updates, some by environment, third-party applications, add-inns, etc. It is not possible to document all of them. This section of the documentation is designed to show the most common issues and the possible solutions/workarounds.
**Given the article has recently been updated, I suspect that you've had a flurry of users with the same problem.** - the only change of the article for the last months is https://github.com/MicrosoftDocs/OfficeDocs-Support/commit/d297f6c45b6b60033a9584691ce7b251a7f41e67#diff-af9777838187972a057853977d4df95764a086901e70fbeee6b47d71d73eb4f3 , and it seems not to be related to the issue you describe.
**The only explanation for a root cause appears to be that a routine update to the application has flipped this setting.** - is there any chance you could provide the list of updates, after installation of which the problem started?
Thank you

**Comment by nam31** [comment]
@AurelianoLobato Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
