### ISSUE TITLE
Access SQL Server ODBC errors on passthroughs returning large data sets.

### ISSUE THREAD

**Issue by ScrabbyOne** [MicrosoftDocs/OfficeDocs-Support#1344]
A similar thing to this started happening yesterday.  Access 2016 > SQL Server Express. Running stored procedures via SQL pass-throughs, when a large data set is returned, ensuing stored procedure calls generate ODBC errors--until the last record of the large data set is visited! This workaround is NOT by any means acceptable. We routinely call a series of SP's in VBA behind our forms.

Again, this is new behavior not observed before in this environment. The Access front-end still works perfectly against SQL Server Express in a different environment. Does not affect calling tables or views--just SQL pass-throughs.

What gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5b14e5-bdf1-8137-68a9-f12859c5794f
* Version Independent ID: 273126a8-6870-4f7c-1a83-16a51be445c2
* Content: [Error (ODBC--call failed) when you open a table that is linked to a SQL Database instance - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/error-opening-sql-linked-table)
* Content Source: [Office/Client/access/error-opening-sql-linked-table.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/error-opening-sql-linked-table.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@ScrabbyOne The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The issues section of this repository is intended for product documentation issues only.

The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
