### ISSUE TITLE
I followed the instructions and now I cannot even open Outlook. 

### ISSUE THREAD

**Issue by MaanHamdan** [MicrosoftDocs/OfficeDocs-Support#1389]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a55b51-85d6-f628-581c-5a1c66675933
* Version Independent ID: 9f626f3a-123d-67ca-3aa8-a3443963fe05
* Content: [Outlook for Mac support tools. - Outlook](https://docs.microsoft.com/en-US/outlook/troubleshoot/outlook-for-mac/useful-tools)
* Content Source: [Outlook/OutlookExperts/outlook-for-mac/useful-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/OutlookExperts/outlook-for-mac/useful-tools.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@MaanHamdan The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
