### ISSUE TITLE
What about going down from Monthly to Semi-Annual?

### ISSUE THREAD

**Issue by LarochelleFanny** [MicrosoftDocs/OfficeDocs-Support#139]
Do you have official documentation on how to go down?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d45540-ec98-57d5-7ef3-0190c64d164e
* Version Independent ID: 1b33de41-c3b6-35bc-840f-085007fc3b71
* Content: [How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365)
* Content Source: [Microsoft365/admin/administration/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by SusanBradley** [comment]
https://erwinbierens.com/switch-office-2016-to-monthly-targeted-channel/  Just flip the commands around.  Channel=”Broad” or Channel=”Deferred“  use those terms to roll back.

**Comment by jlriesco** [comment]
You can move to any channel you wish. You just need to specify the correct URL for the channel you want to move to. This will work for moving from Monthly to SAC and vice versa (both ways). Also, the manual step via ‘Update Now’ are so that is takes affect immediately, otherwise the auto update task in Task scheduler will trigger the switch per the default schedule. 

Also, the recommended method to ‘channel switch’ would be through GPO. In the Office Admin Templates, there are GPO settings for which channel to deploy and you can also specify with build number for that channel. The GPOs can move Office between channels as well, both ways. 

NOTE: In SCCM, you cannot channel switch backwards ie, Monthly to SAC. This is an SCCM limitation. If using SCCM you can only move to a newer channel.
