### ISSUE TITLE
Mozilla Firefox support?

### ISSUE THREAD

**Issue by roggenkamps** [MicrosoftDocs/OfficeDocs-Support#1403]
How do I use it with Mozilla Firefox?  I don't use either Microsoft Edge or Google Chrome and I do not intend to use them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c17faf2-0e38-0a98-454c-3c2c4387b37f
* Version Independent ID: d9153b98-dc39-fdd1-a798-07da0caaaa64
* Content: [Microsoft Teams is stuck in a login loop in Edge, Internet Explorer or Google Chrome - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop#resolution)
* Content Source: [Teams/teams-sign-in/sign-in-loop.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-sign-in/sign-in-loop.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by elsandosgrande** [comment]
Here's a short video of the procedure on Firefox (I use Nightly, but it should be applicable on other release channels as well): http://mellemws.my.to/direct/Screencast_from_2021%25E5%25B9%25B405%25E6%259C%258828%25E6%2597%25A5_18%25E6%2599%258251%25E5%2588%258647%25E7%25A7%2592.webm

Firefox doesn't support `*.` or `[*.]` as far as I can tell, which is why I deleted those.

---

Personally, I only needed to add a single exception: https://discourse.mozilla.org/t/firefox-86-total-cookie-protection-strict-enhanced-tracking-protection-etp-is-no-longer-immediately-compatible-with-microsoft-teams-web-app

**Comment by nam31** [comment]
@roggenkamps we are going to close this issue as the article has been updated accordingly. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
