### ISSUE TITLE
WP Clean Up: Support for use it

### ISSUE THREAD

**Issue by isrgarmes** [MicrosoftDocs/OfficeDocs-Support#1422]
We are using the script WPJClean.cmd

While it initially worked in our lab scenario, it doesn’t in the lab of the customer. 

After research it, we think that the reason is because the order in which the accounts are presented: 
In our lab scenario, the account to disconnect is presented first (up in the list), In the customer’s lab, the account is presented last (down in the list). In this case, the first account is the account we use to log on, so it cannot be disconnected (the disconnect button appears in grey), and we think the .exe that the script calls found an error and don’t proceed further. 
 
Is there any way to selectively disconnect the account we want in an automated way?
 
Thanks and best regards.

**Comment by RAJU2529** [comment]
@isrgarmes . Which article are you referring to?

**Comment by isrgarmes** [comment]
Hello,

We have followed this articles:
[https://docs.microsoft.com/en-us/office/troubleshoot/activation/reset-office-365-proplus-activation-state#clear-credentials-from-workplace-join](url)
[https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md](url)

**Comment by msbemba** [comment]
@isrgarmes Thank you for your feedback. I was able to test this script in the lab and it works no matter which account is presented first. In your case, The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri
