### ISSUE TITLE
Room Finder doesn't look like your screenshots.  Is it a bug?

### ISSUE THREAD

**Issue by Kevin-at-MQ** [MicrosoftDocs/OfficeDocs-Support#1436]
This article is dated 3/15/2021, but a January update to our "current channel" Office 365 product appears to have completely changed the look and function of Room Finder.  In fact, the useful calendar in the screenshots on this page is missing from Room Finder now, and our users are reporting it as a bug.  Is it a bug?  If not, you should probably make some changes to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b9c380-0116-3400-1d54-3ee50c924cba
* Version Independent ID: f1ad1b10-c320-61fa-2818-8dfc8b63271c
* Content: [How to control the Room Finder in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/calendaring/room-finder)
* Content Source: [Outlook/Client/calendaring/room-finder.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/room-finder.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **gabesl**

**Comment by msbemba** [comment]
@Kevin-at-MQ Thank you for your feedback.  The document refers to older versions of outlook. On the new version of Outlook, there are changes to the Room finder and It is by design and aims to provide users with a better experience when working with Outlook room finder, if you still don't like it, as a workaround, you could try to revert your office to an earlier version, such as Version 2012 (Build 13530.20316) or earlier. 

You can follow the Q&A about the new room finder on this document- https://docs.microsoft.com/en-us/answers/questions/369455/room-finder-missingchanged.html

Hope this helps! 

Thanks
Sri

**Comment by nam31** [comment]
@Kevin-at-MQ Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
