### ISSUE TITLE
16.7 MS Access Driver Download

### ISSUE THREAD

**Issue by wicky818** [MicrosoftDocs/OfficeDocs-Support#1469]
[Enter feedback here]
Where is the 16.7 MS Access driver available for download? I can only find 16.0.5xxxx available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726d911b-f3e2-e635-d272-a97cfb2c9ab3
* Version Independent ID: 8060b8cf-86e3-b95c-24d7-0c08d0bafd11
* Content: [Database requires a newer version of Access - Office](https://docs.microsoft.com/en-us/office/troubleshoot/access/database-requires-newer-access)
* Content Source: [Office/Client/access/database-requires-newer-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/database-requires-newer-access.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @wicky818 ,
it looks like the driver is not available yet. The version changes to 16.7 after you updating to MS Access 2019 or Access for Microsoft 365. The version of driver available in download center seems to be compatible with MS Access 2016 or earlier
Thank you

**Comment by nam31** [comment]
@wicky818 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
