### ISSUE TITLE
Renaming Teams Folder in SharePoint breaks connection to Teams

### ISSUE THREAD

**Issue by thomps** [MicrosoftDocs/OfficeDocs-Support#1499]
The ability to rename a channel without causing it to rename the corresponding document folder for that channel causes confusion amongst users who access files both in Teams as well as in SharePoint.  The old folder name still appears in the Files tab of the affected channel, and often times the corresponding folder in SP is a completely different name.  This should be looked at as it doesn't make sense.  You can rename both a channel and a folder for that channel in SharePoint separately, however renaming the folder in SharePoint breaks the connection back to Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9bdbac7-8a35-c53c-8b6e-19afb3732430
* Version Independent ID: 163e910e-0749-1383-f8f6-858bec7cbfc5
* Content: [Renamed Teams folder does not rename the same folder in SharePoint Online - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/known-issues/renaming-channel-does-not-rename-folder-sharepoint)
* Content Source: [Teams/known-issues/renaming-channel-does-not-rename-folder-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/known-issues/renaming-channel-does-not-rename-folder-sharepoint.md)
* Service: **msteams**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by msbemba** [comment]
@thomps Thank you for your feedback. You are right, I was able to test this in our lab. This is by design as we have mentioned in the document and we don't see anything in the 2021 roadmap to change this design.  To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Hope this helps!
Thanks
Sri
