### ISSUE TITLE
This really sucks..

### ISSUE THREAD

**Issue by MikeInSwitzerland** [MicrosoftDocs/OfficeDocs-Support#15]
So, what do we do, if we've followed each of these tips, and Excel still point-blank refuses to open Excel files ?   No error, no messages, it just opens Excel with a blank worksheet.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Troubleshoot Excel opening blank when double-click a file icon or file name - Troubleshooting | Office](https://docs.microsoft.com/en-ca/office/troubleshoot/excel/excel-opens-blank)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
Checking this issue.

**Comment by cabliven** [comment]
Any further updates on this? Workaround is to open MS Excel first, then browse to find the document. But it opens "blank" (unless you type in a cell - you can see the content at the top only) when selecting the file without opening MS Excel first.

**Comment by jlriesco** [comment]
We could add as “Method 1” to ensure Office and Windows are updated. That gets a little tough to explain since how you do that depends on the version of Office and Windows. The best Office content we have for this is here: [https://support.office.com/en-us/article/Install-Office-updates-2ab296f3-7f03-43a2-8e50-46de917611c5](https://support.office.com/en-us/article/Install-Office-updates-2ab296f3-7f03-43a2-8e50-46de917611c5)

The best content for updating Windows is here: [https://support.microsoft.com/en-us/help/12373/windows-update-faq](https://support.microsoft.com/en-us/help/12373/windows-update-faq)

Beyond that, I’m not sure what to recommend…the next steps would be to clean boot Windows and Excel to start scoping the issue. It could be that there is something interfering, such as antivirus software, but I’m always hesitant to tell customers to turn off AV software. The next step would be to call support. But, if we want to recommend that, we could say something like:

Method 7: Update your Antivirus
You should ensure your Anti-Virus software is fully up to date and try opening the file again.

**Comment by jlriesco** [comment]
Working on updating this article.

**Comment by waasdorp** [comment]
![image](https://user-images.githubusercontent.com/2167184/62097742-26813400-b245-11e9-86d8-6dc15dea4fb3.png)
click this 
"upcoming features" icon and boom, spreadsheet appears!
