### ISSUE TITLE
Triggering update

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-Support#153]
Hello,
Do we really require to do action as "Start an Office application (such as Excel), and then select File &gt; Account. In the Product Information section, select Update Options &gt; Update Now."
Or with the next Scheduled task this will be triggered automatically and will run update with Monthly channel update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95d45540-ec98-57d5-7ef3-0190c64d164e
* Version Independent ID: 1b33de41-c3b6-35bc-840f-085007fc3b71
* Content: [How to switch from Semi-Annual Channel to Monthly Channel for the Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365)
* Content Source: [Microsoft365/admin/administration/switch-channel-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/administration/switch-channel-for-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
You can move to any channel you wish. You just need to specify the correct URL for the channel you want to move to. This will work for moving from Monthly to SAC and vice versa (both ways). Also, the manual step via ‘Update Now’ are so that is takes affect immediately, otherwise the auto update task in Task scheduler will trigger the switch per the default schedule. 

Also, the recommended method to ‘channel switch’ would be through GPO. In the Office Admin Templates, there are GPO settings for which channel to deploy and you can also specify with build number for that channel. The GPOs can move Office between channels as well, both ways. 

NOTE: In SCCM, you cannot channel switch backwards ie, Monthly to SAC. This is an SCCM limitation. If using SCCM you can only move to a newer channel.

**Comment by lightupdifire** [comment]
Thanks! Maybe handy to add in doc, like FAQ, that it is not mandatory to trigger update after change.

**Comment by simonxjx** [comment]
Please see http://docs.microsoft.com/deployoffice/change-update-channels for latest information.
