### ISSUE TITLE
How is this by design, the recipient of the alert are the same

### ISSUE THREAD

**Issue by andreaslarssonliu** [MicrosoftDocs/OfficeDocs-Support#1576]
How is this by design, the recipient of the alert are the same, the language should not change because the sender is in a different language.

This is unacceptable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eede262-a5f7-d800-0351-9b5a45737e48
* Version Independent ID: d7c2a3ab-337c-90cb-1092-563013dc0348
* Content: [ATP notifications displayed in foreign languages - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/antispam-and-protection/atp-notifications-shown-in-foreign-languages)
* Content Source: [Exchange/ExchangeOnline/antispam-and-protection/atp-notifications-shown-in-foreign-languages.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/antispam-and-protection/atp-notifications-shown-in-foreign-languages.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@andreaslarssonliu Thank you for your feedback. As mentioned in the article it is by design that ATP notification email messages use the preferred language that's set for the sender's system. Since you are requesting a design change,  To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@nam31  I have tested and I could reproduce the issue. I have provided information about requesting a design change. There are no changes required in the document for now.

Thanks
Sri

**Comment by andreaslarssonliu** [comment]
I have made a change request on this through ticket 26056985

**Comment by msbemba** [comment]
Thank you for the update @andreaslarssonliu
