### ISSUE TITLE
1904 is not the current default for Mac Excel

### ISSUE THREAD

**Issue by xSpaceBeaglex** [MicrosoftDocs/OfficeDocs-Support#161]
"By default, Microsoft Excel for the Macintosh uses the 1904 date system" should specify this is the case only for the 2010 and 2007; 1904 is not the current default for Mac Excel. The rest of the document applies to the current versions of Excel. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by sean-rose** [comment]
In the 1900 date system the serial number does not exactly represent "the number of elapsed days since January 1, 1900."  If that were true then January 1, 1900 would be serial number 0 (zero), but instead it's considered serial number 1 (one).

Also, in the 1900 date system 1900 is treated as a leap year even though it wasn't, so it considers serial number 60 to be February 29, 1900, and all dates from March 1, 1900 onward are one serial number higher than they should be.

Lastly, the statement "1,462 days is equal to four years and one day (including one leap day)" is incorrect.  Four years and one day would be 1,461.  The difference is 1,462 instead of 1,461 because the 1900 date system starts with serial number 1 (one) while the 1904 date system starts with serial number 0 (zero).

**Comment by jlriesco** [comment]
This article has been updated.
