### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by andreolira** [MicrosoftDocs/OfficeDocs-Support#1621]
This bug has existed for 18 years?  If your developers can't fix it in 18 years, time to hire some new ones.  This is absolutely ridiculous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b974aa57-35b6-e494-43dc-23dd486938ca
* Version Independent ID: bb658f3e-e4e3-e9a5-bde0-6e0c1c20cfa2
* Content: [Last digits are changed to zeros when you type long numbers in cells of Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/last-digits-changed-to-zeros)
* Content Source: [Office/Client/excel/last-digits-changed-to-zeros.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/last-digits-changed-to-zeros.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello, it is not a bug, excel just follows IEEE 754 specification. It is left as it is on purpose, newer versions of excel uses it to be compatible with older versions. 
Thank you

**Comment by nam31** [comment]
@andreolira Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
