### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by RaTiller** [MicrosoftDocs/OfficeDocs-Support#170]
Following the steps provided still does not enable email notifications when a response is submitted for these forms. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275b5403-3896-cf97-ee66-786dab0b4d61
* Version Independent ID: d51b179c-13f4-24c9-ae6b-e3f04b23e6c0
* Content: [No email notifications for responses to Group Forms - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/no-email-notifications-for-responses-to-group-forms#feedback)
* Content Source: [Microsoft365/enterprise/no-email-notifications-for-responses-to-group-forms.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/no-email-notifications-for-responses-to-group-forms.md)
* Service: **o365-solutions**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **zakirh**

**Comment by JenniferPatterson** [comment]
After following all the steps provided, we are receiving intermittent email notifications to the group when a response is submitted for the forms. About 95% of the time the email is generated, sent and received. The other 5% of the time, it is not triggered at all. This is frustrating as we have missed important client communications that 5% of the time, and we were lulled into thinking it was working because of the other 95%.

**Comment by msbemba** [comment]
@RaTiller Thank you for your feedback. I was able to test the resolution by allowing external senders to email the group. Let us know if the issue persists.

Thanks
Sri

**Comment by msbemba** [comment]
@RaTiller Just circling back to check if the issue persists.

Thanks
Sri

**Comment by nam31** [comment]
@RaTiller Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
