### ISSUE TITLE
Problem with Microsoft services.

### ISSUE THREAD

**Issue by skorpions2000** [MicrosoftDocs/OfficeDocs-Support#1702]
Delisting is not working. You can't delist the IP from blacklist.
My mailserver is state of the art, DNS & RDNS well configured, DMARC, DKIM, SPF, ... but the only company which do not want their paying users to receive mails is Microsoft!
site don't work normally: 
https://sender.office.com/
i get answer:
Step 1: Our messaging service has experienced a temporary issue, please resubmit your information below
More information here:
https://answers.microsoft.com/en-us/outlook_com/forum/omessaging-oother/problem-with-outlook-services/c5b2c7b3-ebfb-44a0-aabb-b7ae1f4952ad
and here:
https://answers.microsoft.com/en-us/outlook_com/forum/omessaging-oother/step-1-our-messaging-service-has-experienced-a/81bf6b53-9e20-48bc-a5a0-8f25838e3bac
Thank for answer.

**Comment by nam31** [comment]
@skorpions2000 The issues section of this repository is intended for product documentation issues only.
Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
Thank you.

**Comment by skorpions2000** [comment]
> @skorpions2000 The issues section of this repository is intended for product documentation issues only.
> Can you please tell us to which article(s) your question applies? This will help us route the issue correctly.
> Thank you.

Ok, please:
https://sendersupport.olc.protection.outlook.com/pm/policies.aspx
Here wrote, what i must doing. And i doing this, but this all not help me. Form don't work. Please read all information what i write, write please on forum too, you have link. Help me please. All is good, problem only with Microsoft services.

Thank you for answer and repair Microsoft form.

**Comment by nam31** [comment]
We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
Thank you for providing feedback.

**Comment by skorpions2000** [comment]
> We are closing this issue as there hasn't been a response from your side regarding the specific article where the issue stems from.
> Feel free to re-open this issue by clarifying the problematic document and we'd be glad to come up with content updates.
> Thank you for providing feedback.

Emm, I am sorry. This is not article? 
https://sendersupport.olc.protection.outlook.com/pm/policies.aspx

**Comment by nam31** [comment]
Hi @skorpions2000 
The issues section of this repository is intended for product documentation issues only.
When you click on "Feedback" for the page on any of the articles on https://docs.microsoft.com/ , the users are directed here.

The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
