### ISSUE TITLE
Advice doesn't work

### ISSUE THREAD

**Issue by MikeRosoft** [MicrosoftDocs/OfficeDocs-Support#175]
The above instructions don't work. The slider "mail to keep offline" is disabled. When I uncheck and then check "use cached exchange mode", it becomes enabled, but changing the value has no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64aa0cd-7717-992d-6960-c4c5acec8e21
* Version Independent ID: 065defa3-391b-c629-ccff-316e906f0ad2
* Content: [Only a subset of your Exchange mailbox items are synchronized in Outlook - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/mailboxes/only-subset-items-synchronized)
* Content Source: [Outlook/Client/mailboxes/only-subset-items-synchronized.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/mailboxes/only-subset-items-synchronized.md)
* Service: **exchange-powershell**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by mreg** [comment]
@MikeRosoft how do you know it has no effect? After some time the ost file gets bigger. Did you checked?

**Comment by MikeRosoft** [comment]
Currently my e-mail account is configured to store one month of e-mails locally (which I believe has been enforced by the domain administrator, and so the above-described roundabout way of changing it wasn't intended). When I change the setting, it has no effect, and the selected value isn't saved either.

**Comment by Stigsch** [comment]
It does not work here either. Trying to read a shared mailbox in office 365. I am the administrator, so I know I did not enforce any limits. Limit is changed to "all", but I still get the message showing messages newer that 12 months.

**Comment by msbemba** [comment]
@MikeRosoft Thank you for your feedback. Once the slider is changed to keep all emails offline, we need to wait for the folder to be up to date in order to scroll down and check for those emails. If you still have an issue, let us know if the change that was made on the slider sticks or does it revert back to the original settings? 

Thanks
Sri

**Comment by msbemba** [comment]
@MikeRosoft Just wanted to circle back to check if the issue persists.

Thanks
Sri

**Comment by nam31** [comment]
@MikeRosoft Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by pluciorx** [comment]
The solution is not complete. 
In many cases there is an filter applied:
![image](https://user-images.githubusercontent.com/29963409/127768201-1fa16672-2694-4dfe-989c-feafa8a69be9.png)
This filter prevents displaying the messages from the server and should be cleared.

**Comment by MikeRosoft** [comment]
> @MikeRosoft Just wanted to circle back to check if the issue persists.

I haven't try this again, because - as I have said - I strongly believe that the mailbox setting is enforced by the domain policy and isn't intended to be changed in the first place.
