### ISSUE TITLE
MAPIInitialize failed with error 0x80004005 == MAPI_E_CALL_FAILED.

### ISSUE THREAD

**Issue by Andmil13** [MicrosoftDocs/OfficeDocs-Support#1756]
In my case, I can not enter since I do not have the outlook application, I have Microsoft 365, how can I solve this without having that desktop application?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 49089935-0986-778f-677a-3ffa63b3198b
* Version Independent ID: 9edfc357-394b-c85f-bddf-3f936e9e3215
* Content: [No se pueden recibir solicitudes de reuniones provisionales ni respuestas - Outlook](https://docs.microsoft.com/es-es/outlook/troubleshoot/calendaring/cannot-receive-requests-of-tentative-meeting-or-responses)
* Content Source: [Outlook/Client/calendaring/cannot-receive-requests-of-tentative-meeting-or-responses.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/calendaring/cannot-receive-requests-of-tentative-meeting-or-responses.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by nam31** [comment]
@Andmil13 The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The issues section of this repository is intended for product documentation issues only.

The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
