### ISSUE TITLE
Can we get the version details to this article?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Support#1757]
Hi team,

When you are writing;

_**Cause**
This issue occurs if the latest Teams updates aren't installed._

The article is written in May 2021, and if I'm still having this issue, then how to confirm that I do have the correct client version from the client (mobile or desktop)?

Or if the client version does have impact to this (as I believe I do have the latest versions), then this "cause" should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1bd85bb-0bdf-a01e-959f-e2c10805c72f
* Version Independent ID: 3197320f-b839-db32-fc66-f2cf81202848
* Content: [Your actual presence status isn't displayed in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-im-presence/presence-not-show-actual-status)
* Content Source: [Teams/teams-im-presence/presence-not-show-actual-status.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-im-presence/presence-not-show-actual-status.md)
* Service: **msteams**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by nam31** [comment]
@Petri-X The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
