### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by ReQ6W7rFnaBxyfb** [MicrosoftDocs/OfficeDocs-Support#1771]
Is there any way to do this in a Word version more recent than 2013?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8286f0-c195-29de-ce90-98053aa6a317
* Version Independent ID: 2db8c94a-848d-c9f9-be49-98086f43eebd
* Content: [Configure the default search engine in Word 2013 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/configure-search-engine-in-word)
* Content Source: [Office/Client/word/configure-search-engine-in-word.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/configure-search-engine-in-word.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @helenclu
* Microsoft Alias: **luche**

**Comment by MaratMussabekov** [comment]
Hello @ReQ6W7rFnaBxyfb ,
this feature was deprecated in versions newer than Word 2013.
Thank you

**Comment by nam31** [comment]
@ReQ6W7rFnaBxyfb Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
