### ISSUE TITLE
Update removes Exchange Back End site certificate binding and causes EMS authentication issues.

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/OfficeDocs-Support#1784]
[There was an issue accessing connecting to EMS after applying this security update to an EX2016 CU21 server. The update removed the certificate bindings from the Exchange Back End site and as a result, authentication would fail. Similar issue is described here https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/error-occur-ems-eac-owa but the resolution was to reapply the certificate.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6e25c6-6890-e03f-f2a4-2584d4fcbe79
* Version Independent ID: 32b85dcb-ed42-bca0-1280-d51af48f7ef4
* Content: [Error in EMS, EAC, ECP, OWA, or Outlook on the web in Exchange Server - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/error-occur-ems-eac-owa)
* Content Source: [Exchange/ExchangeServer/client-connectivity/error-occur-ems-eac-owa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeServer/client-connectivity/error-occur-ems-eac-owa.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@mariosaelikeit The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The issues section of this repository is intended for product documentation issues only.

The best way to get your issue resolved is to contact Microsoft Support.
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at Get support.
Otherwise, you can create a support ticket at Microsoft Support for business.
