### ISSUE TITLE
Teams causing Shutdown not just on Lenovo

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/OfficeDocs-Support#1793]
[Enter feedback here]
I have a Surface 3 which also shuts down.  The power settings shown do not appear on my laptop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5af3a150-76d4-d381-068c-9aa34adbd7c7
* Version Independent ID: f4eda770-f323-a712-d57d-65b2381a8d2f
* Content: [Lenovo Yoga L13 might shut down during Teams meetings - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/troubleshoot/teams-conferencing/lenovo-shut-down-during-meeting)
* Content Source: [Teams/teams-conferencing/lenovo-shut-down-during-meeting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-conferencing/lenovo-shut-down-during-meeting.md)
* Service: **msteams**
* GitHub Login: @LauraM
* Microsoft Alias: **v-matham**

**Comment by RAJU2529** [comment]
@melkinsco , Create new power plan and then adjust it. There is  a registry key to make visible that particular option in powerplan

**Comment by nam31** [comment]
@melkinsco The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The issues section of this repository is intended for product documentation issues only.

The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
