### ISSUE TITLE
The behavior is not consistent

### ISSUE THREAD

**Issue by fperre** [MicrosoftDocs/OfficeDocs-Support#182]
If I share an item using the "Direct access" (not using the "link giving access"), and then I remove the user permission, the column is updated and the user removed from the list. 
The behavior is not consistent in the two different ways of assigning permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a92366-f8a4-0261-d508-a5f9db54b2a3
* Version Independent ID: 42cd3349-a3a8-8d9f-85be-85801014053b
* Content: [Shared With column displays users who no longer have access to a document - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/sharing-and-permissions/shared-with-column-users-no-access)
* Content Source: [SharePoint/SharePointOnline/sharing-and-permissions/shared-with-column-users-no-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/sharing-and-permissions/shared-with-column-users-no-access.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by VLG17** [comment]
@fperre Are you still seeing this issue? I tried to reproduce it, but was unable to.

If you can still reproduce this issue, I advise you to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).

Otherwise, you can create a support ticket using [Microsoft Support for business ](https://support.serviceshub.microsoft.com/supportforbusiness).
