### ISSUE TITLE
Page Setup does not honour page size selection

### ISSUE THREAD

**Issue by simongrey-LEX** [MicrosoftDocs/OfficeDocs-Support#200]
Whenever trying to print a document to a physical printer or even to a PDF file, MS Word does not honour the page size selection whether the changes are made in the printer properties, page setup or both.

I discovered this when an end user in the US tried to print something onto A4 paper, MS Word would not print onto the A4 paper, instead it defaulted to the region default of Letter. I tested this and had the same problem is reverse (I'm in the UK - my default is A4).

The same thing happens when trying to print onto A5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9fe9af-4cef-c8e6-40d9-badca9d92457
* Version Independent ID: 72200e18-cf1c-dbac-2991-485ad22013ef
* Content: [The printer settings are ignored when you print a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/printer-settings-not-used#feedback)
* Content Source: [Office/Client/word/printer-settings-not-used.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/printer-settings-not-used.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by nam31** [comment]
@simongrey-LEX the article for which feedback was provided has now been replaced. Updated information about printing documents is available at [Print your document - Word (microsoft.com)](https://support.microsoft.com/en-us/office/print-your-document-cebc3705-c949-42f6-8ed9-534943e1ab5c?wt.mc_id=fsn_word_save_and_print&ui=en-US&rs=en-US&ad=US).
If you are still facing the issue, the best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
