### ISSUE TITLE
This no longer works in Office 365

### ISSUE THREAD

**Issue by zippy72** [MicrosoftDocs/OfficeDocs-Support#228]
I'm trying to use this to get around the "universal undo" stack, but Excel 365 just ignores the setting completely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970cf317-aa45-6f08-5edc-f40825391dca
* Version Independent ID: bc3709a7-0210-c17b-b130-79aa14a956d8
* Content: [Force Excel to open in a new instance by default - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/force-excel-to-open-new-instance#feedback)
* Content Source: [Office/Client/excel/force-excel-to-open-new-instance.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/force-excel-to-open-new-instance.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by pebravos** [comment]
I've been using this feature for years and it has been crucial in times when Excel (and other Office apps) crashed several times per day, so that only one file closes and potentially gets damaged. 
The universal undo is another big problem for someone that works everyday with multiple workbooks simultaneously.
Macros running in the background (e.g.: monitors) is yet another problem when you only have one instance running because the code stops when you're editing a cell, etc..
Please get DisableMergeInstance working again.

**Comment by todmccoy** [comment]
We have confirmed that the setting works with O365 and is available to those users. If you have any other issues, please contact Microsoft Support (http://support.microsoft.com/contactus).
