### ISSUE TITLE
Lync Server 2013 and 2010

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-Support#352]
Can we have clarification that this does have the same issue on 2013/2010 but due to them being out of mainstream support they are not getting the update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6e323a-6fb2-c1a6-3afa-b88ed1ad419c
* Version Independent ID: ca05aa94-6799-3961-d83b-8fab9cf83be1
* Content: [Chrome SameSite cookie behavior effect on customer applications - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications)
* Content Source: [Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/miscellaneous/chrome-behavior-affects-applications.md)
* Product: **office 365**
* GitHub Login: @MaryQiu1987
* Microsoft Alias: **v-maqiu**

**Comment by TobieFysh** [comment]
@hpsin Can we have an update to say if this does (or does not) affect Lync Server 2010 and 2013 please.

**Comment by hpsin** [comment]
You're correct - they're out of mainstream support and are not getting an update.

**Comment by TobieFysh** [comment]
Thanks @hpsin - looking at the table about which updates are coming out SharePoint 2010 *is* getting updates even though it is out of Mainstream support as of 13th Oct 2015 and so is SharePoint 2013 which was out of Mainstream support on 10th April 2018..... Is Lync Server being treated differently for a specific reason?

**Comment by TobieFysh** [comment]
@hpsin - any updates?

**Comment by hpsin** [comment]
Hey @TobieFysh - have you tested with Chrome Beta 81 with the flags enabled and seen issues with Lync Server 2013/2010?

**Comment by TobieFysh** [comment]
@hpsin - I've not seen any issues with 2015/2019 so not actually sure where the issues are. There doesn't appear to be any KB published that tells us what the impact will be or how to test. As this appears to be around authentication the only things I can think of are dialin, meet and scheduler. If Microsoft can give direction of what is broken then I'll be happy to undertake testing.

**Comment by hpsin** [comment]
Hi @TobieFysh - I reached out to the Lync team and they responded: 

In general, the issues we’ve found are minor, in a few non-mainstream user scenarios and have workarounds.  As such, we have decided (at this time) to follow standard lifecycle policy of only fixing the server products that are in mainstream support (i.e. SfB 2015 and SfB 2019).  Lync 2010 and Lync 2013 are in Extended Support, which is Security fixes-only.  This SameSite topic is not a Security issue.  This is no different from all of the other bug fixes we ship in supported products and don’t ship in non-supported products.

We have occasionally, due to extraordinary circumstance that negatively affect our customers, responded to external forces and decided to ship non-security fixes for products in Extended Support.  At this time, this SameSite change does not appear to meet the criteria for taking that unusual action.

**Comment by joinimran** [comment]
Hi @TobieFysh, thank you for your feedback.
I am working on this issue and will provide you with an update soon.

**Comment by joinimran** [comment]
Hi @TobieFysh, Lync server 2010 and 2013 are in extended Support which means it will get security fix updates but it will not get any feature update. Your request is a feature update since it in extended Support so it can not be possible.
For reference visit this link:https://docs.microsoft.com/en-us/lifecycle/products/microsoft-lync-server-2013

**Comment by nam31** [comment]
@TobieFysh Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
