### ISSUE TITLE
My Document has been corrupt and i cannot open it

### ISSUE THREAD

**Issue by webby2103** [MicrosoftDocs/OfficeDocs-Support#386]
[Centuries.docx](https://github.com/MicrosoftDocs/OfficeDocs-Support/files/4245042/Centuries.docx)

can anybody help open the document and recover it?

**Comment by nam31** [comment]
@webby2103 The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
