### ISSUE TITLE
Unable to Reproduce

### ISSUE THREAD

**Issue by TausifJam** [MicrosoftDocs/OfficeDocs-Support#397]
office 365 Owners Group  are automatically added a Site Collection Administrator when the Office 365 Group is created, hence even if the Owners are not in the Members, they are able to get the results returned.
So far I have checked in Microsoft 365 search box and Enterprise Search Center
Have found no issues even when Owners are not in Members of Office 365 Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d363df6-b80d-2358-7f74-5703050deb22
* Version Independent ID: 25b8cfca-81f0-fd00-da2f-4ffdd0a6a267
* Content: [Search results don’t appear for group owners after creating a new Office 365 group - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-dont-appear-for-group-owners#feedback)
* Content Source: [SharePoint/SharePointOnline/search/search-results-dont-appear-for-group-owners.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/search/search-results-dont-appear-for-group-owners.md)
* Service: **sharepoint-online**
* GitHub Login: @todmccoy
* Microsoft Alias: **v-todmc**

**Comment by OJ-SEASI** [comment]
I have been troubleshooting a search issue for a couple weeks and I was made aware of this article today.

I have been able to reproduce the issue on 3 separate Office 365 tenants, all located in Canadian datacenters: 2 are regular tenants and one is EDU.

To reproduce, you navigate to the Teams Admin Center and create a new Team from there:
https://admin.teams.microsoft.com/teams/manage

The associated O365 Group created during that process presents the issues described in this article for Owners ( non-functional search experience).

Navigate to your tenant Azure Active Directory Group management page:
https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/AllGroups

 Open the O365 Group created for that new Team, add yourself as a member and search works instantly.

I have also just tried to create a new MS Teams directly from the Teams application (WebApp), and search also seems to not be working for the user who created it (Owner by default). I will verify in 24h as newly created MS Teams may need some time to "settle". 

This issue was noticed on December 21st. As I rely heavily on search across my devices (all apps with data stored on SharePoint site collections affected), I believe I would have noticed very quickly.

Note that I am still getting results from my OneDrive and legacy (classic) SharePoint sites such as PWA when running a search from the SharePoint search box found on the main SharePoint Home (page when clicking on SP icon from the waffle menu).

**Comment by OJ-SEASI** [comment]
Looks like it is only reproducible when creating a new MS Team from the Teams Admin Center. When using the desktop or Web App, it correctly assigns **Edit** permissions to the creator of the MS Team on the SharePoint side:

![image](https://user-images.githubusercontent.com/77409669/104510852-30762e80-55c2-11eb-9c3b-c927bb9d3bc9.png)

Azure AD does not see the Owner in the Member section but shows that there is 1 **Direct member**

![image](https://user-images.githubusercontent.com/77409669/104511109-a11d4b00-55c2-11eb-92b8-492aaf14d4c9.png)

The Office 365 Group with Owners affected by this search issue does not show any **Direct Members**

![image](https://user-images.githubusercontent.com/77409669/104512250-4edd2980-55c4-11eb-81d0-dde466bf9172.png)

I looked for **Direct Members** information but did not find much information, also thought that Direct Members were the sum of Owners and Members!
https://stackoverflow.com/questions/64945145/azure-ad-group-membership-vs-direct-members

**Comment by OJ-SEASI** [comment]
Do not know if it is by design but some sort of warning should be made to admins to avoid confusion: when you create a new Team from the Admin Center, the creator and any additional Owners you add during this creation process will have full privileges except for a broken SharePoint search (need to have **Edit** permissions on the SharePoint side, **Full Control** not enough!).

![image](https://user-images.githubusercontent.com/77409669/104603929-497af000-5653-11eb-83d6-6c523b7748ae.png)

The fix is to add Owners as Members of the associated O365 Groups tied to the newly created Team...

Case closed!

**Comment by msbemba** [comment]
@TausifJam Thank you for the feedback. I was able to test this and the issue appears only when the group is created from Microsoft teams admin center. I have added the cause to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Support/pull/1482

Thanks
Sri

**Comment by msbemba** [comment]
@TausifJam The reason has been explained in the More Information section. And this note is about one scenario that results in the cause.

Hope this Helps!

@nam31 There are no changes required in the document.

Thanks
Sri

**Comment by msbemba** [comment]
@nam31  The reason has been added and explained in the more information section. This is good to be closed.

Thanks
Sri

**Comment by nam31** [comment]
@TausifJam 
Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
