### ISSUE TITLE
Map a Network Drive : Step3

### ISSUE THREAD

**Issue by pgarg1107** [MicrosoftDocs/OfficeDocs-Support#41]
The step says View in File Explorer option is not available in Microsoft Edge, Chrome or Firefox. I could not find it in Internet Explorer as well. It would be better if we can get the information where exactly we can find this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Troubleshoot mapped network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/support/administration/troubleshoot-mapped-network-drives?redirectSourcePath=%252fen-us%252farticle%252ftroubleshoot-mapped-network-drives-that-connect-to-sharepoint-online-ef399c67-4578-4c3a-adbe-0b489084eabe#feedback)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by JaredRic** [comment]
In the modern UI:

1. Open the document library in **Internet Explorer**
2. Select the list view drop down in the top right. E.g. All Documents
3. Click **View in File Explorer**

In the classic UI:

1. Open the document library in **Internet Explorer**
2. Select the **Library** tab in the ribbon.
3. Click the **Open with Explorer** in the Connect & Export section of the ribbon. Note: If you window is small this might be hidden under a drop down or just show a button instead of the full text.

Hope that helps!

**Comment by Balaji513** [comment]
Added SharePoint site in trusted sites in IE to map SharePoint site locally. Getting below error

The Mapped network drive could not be created because the following error occurred.

Access Denied. Before opening files in this location, you must first add the web site to your trusted site list, browse to the web site, and select the option to login automatically

Please find the attachment for reference.
![Sharepoint-Locally](https://user-images.githubusercontent.com/43398699/68294074-47172080-00b5-11ea-9f4e-3341745cda5a.png)

**Comment by ryanturcotte** [comment]
If my organization doesn't provide me with the "Stay signed-in option" , like it redirects to an ADFS sign-in, is this possible?

**Comment by nam31** [comment]
Hi @pgarg1107 , the article that you have referred to has been updated since you raised this issue. 
Are you still facing this issue?

**Comment by nam31** [comment]
@pgarg1107 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
