### ISSUE TITLE
Set location manually

### ISSUE THREAD

**Issue by golledge65** [MicrosoftDocs/OfficeDocs-Support#417]
When you are working remotely, is that not the time when you might need to tell people where you actually are?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1969df5-e283-719a-0078-fc304a3b6bd0
* Version Independent ID: cb80f866-b8fd-1468-6508-c1aa85a7bb54
* Content: [Can't set location in Lync from virtual machine or remote desktop connection - Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/online-configuration/cant-set-location-in-lync#feedback)
* Content Source: [SkypeforBusiness/SkypeOnline/online-configuration/cant-set-location-in-lync.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SkypeforBusiness/SkypeOnline/online-configuration/cant-set-location-in-lync.md)
* Service: **skype-for-business-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by maphew** [comment]
yes, exactly.

**Comment by NeverEnoughCoffeeMan** [comment]
WAIT! Are you inferring that I might know my whereabouts better than Lync's Location Information Service? Unpossible!

**Comment by claudialake** [comment]
Lync disables the Set Your Location field because it can't accurately rely on the location information through a virtual host. Lync uses the Location Information Service (LIS) based on a network map to detect your location. Then, Lync automatically publishes your location to the organization. However, when you use a virtual machine, or you connect to a virtual machine by using a remote desktop connection, the LIS can't accurately determine your location. Therefore, the location is unavailable.

**Comment by golledge65** [comment]
Maphew has it.  The issue is that the user has no way of telling their teammates where they are when they are working remotely.  It's nice that LIS sets it when it can, but the need to communicate that information does not go away just because it can't.
