### ISSUE TITLE
Invalid instructions

### ISSUE THREAD

**Issue by et3rae** [MicrosoftDocs/OfficeDocs-Support#454]
None of these instructions are valid for Azure AD Connect.  Is there a similar process for AAD Connect?  The enable-msonlinerichcoexistence isn't a command with AAD Connect.  The import-module DirSync isn't valid, etc.  But I'm having a problem with the exchange attributes writing back.

Unless they just don't do that any longer...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee01f9a2-888c-58d9-ab2e-6381a0c43e60
* Version Independent ID: d91b824b-e8d3-3c5b-e57a-8802180f2c7e
* Content: [Exchange Online attributes aren't written back to on-premises AD directory service - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/federation/attribute-not-written-to-azure-ad#feedback)
* Content Source: [Exchange/ExchangeHybrid/federation/attribute-not-written-to-azure-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/federation/attribute-not-written-to-azure-ad.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by ssjaronx4** [comment]
I have had the same issue. We have enabled the Exchange Hybrid option in AAD Connect (latest build) and it hasn't generated the rich coexistence groups (no prompt anywhere in the wizard unlike the article suggests). We get a failure with the export of properties back to AD (permissions-issue 8344). I came across the same page and attempted to follow the instructions, but the DIRSYNC module no longer exists. I tried importing all of the other PS modules under the AAD Connect folders but none contain Enable-MSOnlineRichCoexistence. 

Does AAD Connect still need to create the Rich Coexistence group or is that legacy (and hence its probably failing for a different reason)?

**Comment by ComputerHabit** [comment]
I had this issue as well.  It turned out to be not properly adding the new domain to the Exchange Installation and then running hybrid.  Once I ran hybrid, after a few hours of provisioning I guess, items updated as they should.

So run hybrid any time you make a change to Exchange in house.  That goes for cert updates as well.

**Comment by msbemba** [comment]
@et3rae Thank you for your feedback. This document pertains only to the ADsync tool. The enable rich coexistence is no longer available with Azure AD connect.

These attributes are written back from Azure AD to on-premises Active Directory when you select to enable Exchange hybrid. Depending on your Exchange version, fewer attributes might be synchronized.

For more information, visit -https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@et3rae Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
