### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-Support#465]
What timezone is the "LastAccessed" column in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a93c78d-ed18-2fda-d8bb-9f60f64fbc0f
* Version Independent ID: a79b1742-f841-c8a5-71f6-1c1dda533d6a
* Content: [How to use mailbox audit logs in Office 365 - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/audit-logs/mailbox-audit-logs)
* Content Source: [Microsoft365/Compliance/audit-logs/mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/Compliance/audit-logs/mailbox-audit-logs.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by sowjanya365** [comment]
Hi @sysadmin-scs 

"LastAccessed" parameter shows the time in owners timezone. Hope this clarifies your query. 

Thank you!

**Comment by nam31** [comment]
@sysadmin-scs Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
