### ISSUE TITLE
Which AD attribute, exaclty, need to be changed? "telephonenumber"?

### ISSUE THREAD

**Issue by fborup** [MicrosoftDocs/OfficeDocs-Support#468]
Which AD attribute, exaclty, need to be changed? "telephonenumber"?

And is important to mention a possible non-replicated attribute from AADconenct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e032f2e-3e64-80cb-ff0f-f8f2af105063
* Version Independent ID: 468d106a-b28f-d005-f3a6-76d05163e198
* Content: [Can't change office phone number when setting up Azure Multi-Factor Authentication - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/cant-change-phone-number-with-mfa#more-information)
* Content Source: [Microsoft365/admin/active-directory/cant-change-phone-number-with-mfa.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/cant-change-phone-number-with-mfa.md)
* Product: **office 365**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by sowjanya365** [comment]
Hi @fborup 

Please update the "telephoneNumber" attribute in the "attribute editor". Hope this clarifies your query. 

Thank you!

**Comment by nam31** [comment]
@fborup Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
