### ISSUE TITLE
OneNote 2016 taskbar icon still not showing

### ISSUE THREAD

**Issue by dyglesias** [MicrosoftDocs/OfficeDocs-Support#511]
I did everything in the guide, but still the taskbar icon not showing. Even if I try to manually execute the onenoteM.exe nothing happens.
I have uninstalled and reinstalled OneNote2016 completely without success.
What else can I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1c4d8f4-6e97-5f66-6951-860c805a6fbb
* Version Independent ID: b2ec4fb3-2a88-936c-bf2c-e5ca90333255
* Content: [The Open new side note icon is missing from the Windows notification area - Office](https://docs.microsoft.com/en-us/office/troubleshoot/onenote/open-new-side-note-missing#feedback)
* Content Source: [Office/Client/onenote/open-new-side-note-missing.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/onenote/open-new-side-note-missing.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @Lucciz
* Microsoft Alias: **v-zolu**

**Comment by msbemba** [comment]
@dyglesias Thank you for your feedback. The document has been moved to Onenote Help& learning.

I suggest you reset the OneNote to check if the issue can be fixed.
Before you reset, please make sure these data have been synced to the cloud.
Or please backup them in your local path because this operation will permanently delete the app’s data on this device, including your preferences and sign-in details.
For resetting the OneNote:
1.Click the Start icon and choose setting.
2.Click Apps option and find the OneNote icon.
3.Click it and choose Advanced options.
4.On the page, you will see Reset option and reset it.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@dyglesias Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
