### ISSUE TITLE
Can I reset the cache?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-Support#521]
If the cache gets messed up for some reason, can I simply uncheck the 'Use Cached Mode" box and then re-check it?  Will that delete the exiting cache and then create a new one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d3d674-d9a9-f5bb-96c8-17968827e41d
* Version Independent ID: b497b804-c05b-ca61-d773-4e95e27763ab
* Content: [Plan and configure Cached Exchange Mode in Outlook 2016 for Windows - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/deployment/cached-exchange-mode)
* Content Source: [Outlook/Client/deployment/cached-exchange-mode.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/deployment/cached-exchange-mode.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by RAJU2529** [comment]
@kelemvor33. Sorry, i do not use outlook, so I can't comment. You can post your query in answers.microsoft.com to get required answers.

**Comment by msbemba** [comment]
@kelemvor33 Thank you for your feedback. When you use Cached mode, the OST file on your hard drive is used to store and search messages. In case, you un-check and check cached exchange mode, then the same OST file will be used the next time you restart outlook. So preferably, if you have a messed up cache, It is easier to create a new Outlook profile (https://support.microsoft.com/en-us/office/create-an-outlook-profile-f544c1ba-3352-4b3b-be0b-8d42a540459d), which downloads a new OST file.

Since this document does not include any troubleshooting steps for cached exchange mode, We will not be able to add the information here.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@kelemvor33 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
