### ISSUE TITLE
No "check disk permissions" option in Method 2

### ISSUE THREAD

**Issue by JESii** [MicrosoftDocs/OfficeDocs-Support#538]
Ran disk utility and "First Aid", but there was no option to "check disk permissions"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5413e44-74f0-4317-90cc-f4ee40d79cb1
* Version Independent ID: 2146e0ef-8148-3432-44d5-c3d5642dde43
* Content: [Unable to start Excel for Mac - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/fails-starting-excel-mac#feedback)
* Content Source: [Office/Client/excel/fails-starting-excel-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/fails-starting-excel-mac.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@JESii Thank you for your feedback. The option in Method 2 is called Repair disk permissions and can be found under the First Aid Tab.

![image](https://user-images.githubusercontent.com/45987684/120246226-3e84cd00-c28d-11eb-8c47-10c43f5f2f85.png)

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@JESii Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
