### ISSUE TITLE
Registry Change Made no difference Encrypt-Only Still listed

### ISSUE THREAD

**Issue by bjnesbitt** [MicrosoftDocs/OfficeDocs-Support#549]
Registry Change Made no difference Encrypt-Only Still listed  

Outlook 2016 and O365 version both are still showing Encrypt-Only after restart and user logged on. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94fc938c-da82-03d8-9fbb-a71c961e0f1e
* Version Independent ID: 738b0fe6-49a1-0819-c124-414fcd07df01
* Content: [Disabling the Encrypt-Only feature in Outlook - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/office-message-encryption/disable-encrypt-only)
* Content Source: [Microsoft365/Compliance/office-message-encryption/disable-encrypt-only.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/Compliance/office-message-encryption/disable-encrypt-only.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Reeced40** [comment]
@bjnesbitt thank you for reaching out. I'll look into this. Please let me know if this is a document issue and if there is anything that needs to be changed in the article, or is it a product issue?

**Comment by Reeced40** [comment]
@bjnesbitt I see the article has been updated with more information since you raised the issue. See in the beginning of the article:
"Summary
In Microsoft Outlook for Office 365, when the new Office 365 Message Encryption Capabilities feature is enabled, Encrypt-Only  is added as a new ad-hoc template. Encrypt-Only  enables message encryption without rights restrictions. This article describes how to disable the Encrypt-Only option in Outlook.

For more information about the feature, see Encrypt-Only option for emails.

More information
You can disable the Encrypt-Only option on the Encrypt  list without also disabling Message Classification. To do this, apply the following registry key.

 Warning

This section, method, or task contains steps that tell you how to modify the registry. However, serious problems might occur if you modify the registry incorrectly. Therefore, make sure that you follow these steps carefully. For added protection, back up the registry before you modify it. Then, you can restore the registry if a problem occurs. For more information about how to back up and restore the registry, click the following article number to view the article in the Microsoft Knowledge Base:

322756 How to back up and restore the registry in Windows"

Please let me know if you need further assistance.

**Comment by nam31** [comment]
@bjnesbitt We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
