### ISSUE TITLE
admx and adml

### ISSUE THREAD

**Issue by Calle2003** [MicrosoftDocs/OfficeDocs-Support#553]
Why the classic adm and not newer admx and adml? Would it be done differently with admx and adml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce321185-d005-bcfb-74bf-a23bd31850a6
* Version Independent ID: f96194ef-a823-7f29-fda3-4dc6e84f6831
* Content: [How to configure the default e-mail client using Group Policy - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/group-policy/configure-email-client-using-policy#feedback)
* Content Source: [Microsoft365/admin/group-policy/configure-email-client-using-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/group-policy/configure-email-client-using-policy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@Calle2003 Thank you for your feedback. You can use ADMX or ADML template and add it to the  Local Group Policy Editor.  You will need to save it as .ADMX or.ADML before you add it to the Local group policy editor.

Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
@Calle2003 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
