### ISSUE TITLE
Office 365 support for MS-OFBA forms authentication

### ISSUE THREAD

**Issue by olleozon** [MicrosoftDocs/OfficeDocs-Support#576]
Hi!
Do you know if Office 365 will support MS-OFBA forms authentication (over https) in the foreseeable future?
Background: Office 365 ability to access legacy Web DAV server. 
Compared to Basic Authentication and Exchange Online – April 2020 Update
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0f4811-5498-a666-064d-e1292a2ab2cc
* Version Independent ID: ee127f8e-ea55-9cad-b063-7529b3561481
* Content: [A custom HTML login page doesn't render correctly in an Office application - Office](https://docs.microsoft.com/en-us/office/troubleshoot/authentication/custom-html-login-page-not-render-correctly)
* Content Source: [Office/OfficeExperts/authentication/custom-html-login-page-not-render-correctly.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/OfficeExperts/authentication/custom-html-login-page-not-render-correctly.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **warrenr**

**Comment by msbemba** [comment]
@olleozon Thank you for your feedback. O365 supports form-based authentication when the domain is federated. let us know if you have any specific issues with authentication.

Thanks
Sri

**Comment by catmanjan** [comment]
> @olleozon Thank you for your feedback. O365 supports form-based authentication when the domain is federated. let us know if you have any specific issues with authentication.
> 
> Thanks
> Sri

Is there a way to prevent the warning users receive when first receiving an MSOFBA prompt? See here for more info: https://stackoverflow.com/questions/61523513/latest-version-of-microsoft-office-block-ms-ofba-requests/67031316

**Comment by msbemba** [comment]
@catmanjan Thank you for your feedback. Disabling Basic authentication has been postponed. If you have security defaults enabled it will block basic authentication. If you have Basic auth enabled and still receive this error, The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).


Thanks
Sri

**Comment by catmanjan** [comment]
@msbemba I was not talking about Basic authentication - I am talking about Forms authentication

https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-ofba/30c7bbe9-b284-421f-b866-4e7ed4866027

The message says "Forms-based authentication is a legacy authentication method for Office resources that are not protected by Azure Active Directory (AAD) or Microsoft account (MSA)."

Is Microsoft providing a way for partners to integrate with AAD/MSA for on-prem Office authentication?

**Comment by msbemba** [comment]
@catmanjan Sorry about the confusion. While I don't see this in the roadmap, you will be able to request this via our feedback Section to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Thanks
Sri

**Comment by nam31** [comment]
@olleozon Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
