### ISSUE TITLE
No problem fix after going through both steps

### ISSUE THREAD

**Issue by flxflks** [MicrosoftDocs/OfficeDocs-Support#60]
Hi, I am still encountering the problem even after using both solutions, deleting the account from my profile and adding it again.
Running specs: Windows 10 Education on a 64-bit system. The email account is connected to outlook.com. It is a second account after my work account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003b3cba-164f-4443-ad85-9509a54a125b
* Version Independent ID: c237b7a5-7b05-900d-adab-df43daed3d8a
* Content: [You can't successfully dismiss calendar reminders in Outlook - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-reminders/cannot-dismiss-outlook-calendar-reminders)
* Content Source: [Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-reminders/cannot-dismiss-outlook-calendar-reminders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by mfalkvidd** [comment]
I was also unable to dismiss reminders, even after trying /cleanreminders and the recommended mfcmapi fix.

Turned out I was using Microsoft Flow to sync events from my Google calendar to my Outlook 365 Calendar. The guide I followed recommended to set the "reminder" setting to -1 in the flow (presumably to avoid getting double reminders).

**-1 is unsupported and makes it impossible to dismiss the reminder.**

The long-term solution is for Microsoft Flow to support disabling reminders. Please vote for https://powerusers.microsoft.com/t5/General-Flow-Discussion/How-can-I-set-none-to-Reminder-of-action-quot-Office-365-Outlook/td-p/16816

In the meantime, I have configured Microsoft flow to set the reminder to 0. This means I'll get a reminder when the event starts (in addition to the real reminder on my google calendar). Annoying, but better than not being able to dismiss the reminder.

I used mfcmapi to edit all the reminders that had value -1. Open the reminder as table. For each reminder, select it and look for the PidLidReminderDelta setting. If it is -1, set it to 0.

**Comment by nam31** [comment]
@flxflks, this article has been updated recently. Please let us know if your issue is resolved now. Thanks

**Comment by nam31** [comment]
@flxflks We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.

**Comment by flxflks** [comment]
@nam31 Hi, unfortunately the problem persists even after trying out the updated fixes.

**Comment by MaratMussabekov** [comment]
Hello @flxflks ,
this section of documentation is dedicated for troubleshooting Exchange Hybrid deployments, it doesn't cover Outlook.com.
![image](https://user-images.githubusercontent.com/48041687/125663322-89249eb9-7ffa-4b1d-b509-dbe6ff86fadd.png)
You can contact support team on [Outlook.com support portal](https://support.microsoft.com/en-us/office/get-help-with-outlook-com-40676ad0-c831-45ac-a023-5be633be798d) or [MS Office Outlook support portal](https://support.microsoft.com/en-us/outlook).
**It is a second account after my work account.** - I would recommend to try to create a new profile, and add the outlook.com account only, and check whether problem is gone.
Also you can try some basic actions, like installing the latest updates, repair the MS Office installation, etc.
Thank you!
