### ISSUE TITLE
What about sharing with internal people?  I get this same error when I select someone within my own domain.

### ISSUE THREAD

**Issue by ryanwga** [MicrosoftDocs/OfficeDocs-Support#664]
Is delegate access the only way to share with internal people then?  If so, this causes confusion as to when to use Calendar Sharing vs Delegate access.  Also, it appears delegate access grants additional permissions that Sharing doesn't "Send As/On Behalf".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743aa69d-a096-c888-df7e-e3b3c237946e
* Version Independent ID: ec11fd15-3bf3-f41d-cf69-920fdc583440
* Content: [Policy does not allow granting permissions at this level when share calendar - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/calendar-sharing/policy-permissions-issue)
* Content Source: [Exchange/ExchangeHybrid/calendar-sharing/policy-permissions-issue.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeHybrid/calendar-sharing/policy-permissions-issue.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello @ryanwga ,
**Is delegate access the only way to share with internal people then?** - no, you can still use calendar sharing
**when to use Calendar Sharing vs Delegate access.** - calendar sharing is only when you want to share calendar information (for example, with colleagues). delegation is used when you want someone to manage your calendar (for example, personal assistant)
**Also, it appears delegate access grants additional permissions that Sharing doesn't "Send As/On Behalf".** - it is expected, since without these permissions delegate cannot accept/decline meetings on your behalf.
Thank you

**Comment by nam31** [comment]
@ryanwga Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
