### ISSUE TITLE
Looks to me like the folder in question should be inetcache\content.word rather than inetcachecontent.word

### ISSUE THREAD

**Issue by gamaha** [MicrosoftDocs/OfficeDocs-Support#669]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f069189a-7af4-d6df-1509-f30af7d3c01d
* Version Independent ID: df260ca7-16dd-d2f8-1de3-91e0b71f67d4
* Content: [Word could not create the work file error message when you save a document - Office](https://docs.microsoft.com/en-us/office/troubleshoot/word/word-could-not-create-the-work-file)
* Content Source: [Office/Client/word/word-could-not-create-the-work-file.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/word/word-could-not-create-the-work-file.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@gamaha thank you for pointing this out. I'm looking into it.

**Comment by lindspea** [comment]
@gamaha I see the article has been updated and is reading as such: INetCacheContent.Word. Please let me know if you still think it needs to be changed.

**Comment by nam31** [comment]
@gamaha Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
