### ISSUE TITLE
Outdated advice

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-Support#686]
In the section "Application compatibility and the 64-bit version of Office" it says Microsoft recommends 32-bit. This is no longer the case, with 64-bit being the default option on the latest versions, and could confuse readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4791c41a-bb52-f3dc-8ecf-9054e8b47549
* Version Independent ID: ef3692f0-8816-782a-cd02-331f898c9238
* Content: [Can't install 64-bit Office with 32-bit Office - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-install-64-bit-office-with-32-bit)
* Content Source: [Office/Client/office-suite-issues/cannot-install-64-bit-office-with-32-bit.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-suite-issues/cannot-install-64-bit-office-with-32-bit.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by lindspea** [comment]
@thommck thank you for pointing this out. I'm looking into it and will make the necessary changes once investigated.

**Comment by nam31** [comment]
@thommck Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
