### ISSUE TITLE
Additional option for fixing the issue

### ISSUE THREAD

**Issue by Bilbottom** [MicrosoftDocs/OfficeDocs-Support#692]
Hi,

I would like to add an additional option to the list, which is what worked for me (it's similar to Option 3).

I had an xlsm file that was opening a blank Excel window. I tried a few of the options, and I couldn't get it to open the workbook correctly.

To fix it, I renamed the file to have an xlsx extension, opened it (which still opened to a blank Excel window), closed it, and then renamed it again to have an xlsm extension. After renaming it, I opened it again and it worked correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a88c46-43bb-92cf-c409-c8b3071b3865
* Version Independent ID: 19f5e98e-36a5-e2e9-39b1-5fc5ae349b50
* Content: [Excel opens a blank screen when you double-click a file icon or file name - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/excel-opens-blank)
* Content Source: [Office/Client/excel/excel-opens-blank.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/excel-opens-blank.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@Bilbottom Thank you for your feedback. The workaround of renaming the file usually fixes issues with a corrupt file extension. An online repair mentioned in option 7 and reset file association in option 5 will be a permanent resolution (Since it fixes the application instead of just the file).

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@Bilbottom Hopefully I answered your question. Let us know if you feel any update is needed on the document.

Thanks
Sri

**Comment by nam31** [comment]
@Bilbottom Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
