### ISSUE TITLE
Helpful, but raises a few questions

### ISSUE THREAD

**Issue by jff1521** [MicrosoftDocs/OfficeDocs-Support#708]
The article made sense and made it possible for me to make the appropriate adjustment.  Since the 1904 date system allows for negative times and is more useful for sports and training, why doesn't Microsoft just convert all sheets to the 1904 system or, absent that for compatibility purposes, just fix the 1900 date system so that it allows for the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8462f7c-3fcb-c891-cca9-8c1ff894d4b0
* Version Independent ID: 78b5d0d6-6de5-e495-20a6-c5b9c34046f7
* Content: [Differences between the 1900 and the 1904 date system - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system)
* Content Source: [Office/Client/excel/1900-and-1904-date-system.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/1900-and-1904-date-system.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@jff1521 Thank you for your feedback. We handle issues or modifications pertaining to documents, Having said that since you are requesting a design change, I'd recommend you to post your idea or vote for a design change  here -https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/9940791-dates-prior-to-1900

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@nam31 There are no changes required in the document as it is by design.

Thanks
Sri
