### ISSUE TITLE
Query not solved.

### ISSUE THREAD

**Issue by AliMamoonRizwan-i2c** [MicrosoftDocs/OfficeDocs-Support#745]
[In that page it was explained that what to do when you are entering long numbers and don't want them to convert the last number into the zero, but it was not explained that what to do while opening the CSV file which already has the large card numbers in this because it automatically converts the last numbers to the zero before  opening the document.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b974aa57-35b6-e494-43dc-23dd486938ca
* Version Independent ID: bb658f3e-e4e3-e9a5-bde0-6e0c1c20cfa2
* Content: [Last digits are changed to zeros when you type long numbers in cells of Excel - Office](https://docs.microsoft.com/en-us/office/troubleshoot/excel/last-digits-changed-to-zeros)
* Content Source: [Office/Client/excel/last-digits-changed-to-zeros.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/excel/last-digits-changed-to-zeros.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by RAJU2529** [comment]
@AliMamoonRizwan-i2c .will you share the entered .csv file .
I will check in officce 2019

**Comment by AliMamoonRizwan-i2c** [comment]
Can i share the screen recording too ?
Okay i will send the file

Best Regards



***************************************
Ali Mamoon Rizwan
Associate Program Manager - Program Operations
i2c Inc.
100 Redwood Shores Parkway, Suite 100
Redwood City, CA 94065
PBX:  +1 650.593.5400 x 4969
Direct:  +1 650.480.5277
Fax: +1 650.593.5402
www.i2cinc.com
***************************************

 Connect With Us

CONFIDENTIALITY CAUTION
This communication (including any accompanying documents) is intended only for the use of the addressee(s) and contains information that is PRIVILEGED AND CONFIDENTIAL. Unauthorized reading, dissemination, distribution or copying of this communication is prohibited. If you have received this communication in error, please notify us immediately by e-mail, telephone or fax and promptly destroy the original communication. Thank you for your cooperation.
________________________________

**Comment by RAJU2529** [comment]
@AliMamoonRizwan-i2c . share video also. it will be useful to analyze

**Comment by AliMamoonRizwan-i2c** [comment]
Okay. Are you from Microsoft or just a common user like me ?

**Comment by RAJU2529** [comment]
@AliMamoonRizwan-i2c . i am common user like you. not from Microsoft

**Comment by msbemba** [comment]
@AliMamoonRizwan-i2c Thank you for your feedback. By design, Excel has a maximum of 15 digits of precision and will round any numbers that follow the 15th digit down to zero, which probably isn’t what you want to happen. In this case, You can empty cells, and then enter numbers after you format the cells as text. Those numbers will be formatted as text.

Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
@AliMamoonRizwan-i2c Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
