### ISSUE TITLE
Not working when having both personal and business accounts

### ISSUE THREAD

**Issue by frankzhangxd** [MicrosoftDocs/OfficeDocs-Support#785]
[Enter feedback here]

one of the employee has both personal and business accounts, we try to sign out and sign in, so we can sign in now automatically with a business account, but every time when we click the SharePoint icon to visite the project, it always asks to pick an account again. in this case, the network location is not accessible unless we keep the IE open and choose the business account to open SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8928ed26-fda0-0e68-a4e1-cc287a5e5699
* Version Independent ID: c6ff303c-a5b4-4890-6d00-82246b92ea45
* Content: [Mapping and syncing network drives that connect to SharePoint Online - SharePoint](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/troubleshoot-mapped-network-drives)
* Content Source: [SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by dariomws** [comment]
Hi @frankzhangxd, thank you for the feedback and sorry for the delay.

Maybe you are not experiencing this issue anymore, but I recommend that you try with the OneDrive sync client instead of mapped network drives.

If you still have issues, the best way to get them resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
