### ISSUE TITLE
File Extension Issue

### ISSUE THREAD

**Issue by maravint** [MicrosoftDocs/OfficeDocs-Support#799]
Hi, 

The script is working fine. But i could see a small issue. While exporting the target file is not getting created with an extension such as .txt or .csv. Because of that i am not able to use the exported file as an source file for a different process. Kindly let me know if i missed any. 

Thanks.

**Comment by RAJU2529** [comment]
@maravint . which article are you referring?

**Comment by maravint** [comment]
Hi,

Below is the article Link, 

https://docs.microsoft.com/en-us/office/troubleshoot/excel/export-text-file-with-comma-quote#:~:text=You%20can%20use%20the%20Print,data%20before%20you%20run%20it.

**Comment by msbemba** [comment]
@maravint Thank you for your feedback. I was able to test it successfully now. 

![image](https://user-images.githubusercontent.com/45987684/120401536-c4704900-c35d-11eb-94e6-f0738cf0ca83.png)

Could you please check and let us know if this is resolved now?

Thanks
Sri

**Comment by nam31** [comment]
@maravint Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
