### ISSUE TITLE
Some examples do not work

### ISSUE THREAD

**Issue by TimonChristl** [MicrosoftDocs/OfficeDocs-Support#80]
For example:

ActiveSheet.Range(Cells(2, 3), Cells(10, 4)).Select

This should be instead

ActiveSheet.Range(ActiveSheet.Cells(2, 3), ActiveSheet.Cells(10, 4)).Select

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bbe6e6-cb2a-50ae-7c2c-cef5c64e6559
* Version Independent ID: 9a187fc7-3fc1-effa-a440-46dc2c8838b6
* Content: [How to select cells or ranges by using Visual Basic procedures in Excel. - Office](https://docs.microsoft.com/en-us/office/troubleshoot/office-developer/select-cells-rangs-with-visual-basic#feedback)
* Content Source: [Office/Client/office-developer/select-cells-rangs-with-visual-basic.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/office-developer/select-cells-rangs-with-visual-basic.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by jlriesco** [comment]
It isn't wrong really wrong or right. For ActiveSheet, it is implied, so both work the same. With the .Select, the sheet has to be active so it doesn't matter if you use ActiveSheet

I've added your suggestion and one more since it also could be simplified to this:

Range(Cells(2, 3), Cells(10, 4)).Select

Thanks.
