### ISSUE TITLE
This fix did not work

### ISSUE THREAD

**Issue by RameshSeervi** [MicrosoftDocs/OfficeDocs-Support#81]
This fix did not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8caf80f-be2c-e901-d3d1-9b19409d085e
* Version Independent ID: b842bc21-a637-b697-9228-7807c9616889
* Content: [Office Applications crash or cannot start - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/office-crash-or-cannot-start#feedback)
* Content Source: [Microsoft365/enterprise/office-crash-or-cannot-start.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/enterprise/office-crash-or-cannot-start.md)
* Service: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by OrlestoneTech** [comment]
Liked like to echo off Ramesh, this suggested fix does not work.  The issue is still occurring, below is a export from Systrack:

 Fault	                                                                Number Faults Affected Systems	 App Version	 Module	                Module Version
outlook.exe   (16.0.4873.1000, mso30win32client.dll, 0000000000156655)	120	      45	         16.0.4873.1000	 mso30win32client.dll	16.0.4849.1000
outlook.exe   (16.0.4861.1000, mso30win32client.dll, 0000000000156655)	283	      57	         16.0.4861.1000	 mso30win32client.dll	16.0.4849.1000

Thanks

Barry

**Comment by WallyCZ** [comment]
This helped:
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\Identity]

"EnableADAL"=dword:00000000

**Comment by OrlestoneTech** [comment]
Hi, thanks for the suggestion but this disables modern authentication and will cause us issues with Exchange online / Office 365.  This issue is getting worse and needs to be looked at.  Thanks

**Comment by vichetsiem** [comment]
temporary fix: run the apps such as excel in safe mode...
C:\users\<user>\excel.exe /safe

**Comment by RameshSeervi** [comment]
Please help us with the cause & resolution. The workaround is not fixing the issue until a new Windows Profile is created or the PC is re-imaged.

**Comment by atadolfo** [comment]
Any resolution?

**Comment by ckssaas** [comment]
05/13/21 - This fix is still not working for latest build 13901.20516 bug; c2r on Win 10 19041. Limping in safe mode.

**Comment by nam31** [comment]
@RameshSeervi The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
