### ISSUE TITLE
teams remove users sometimes shows intermittently

### ISSUE THREAD

**Issue by Yuhan-Meng** [MicrosoftDocs/OfficeDocs-Support#826]
[Enter feedback here]

The teams sometimes shows other owners remove the member, not the exact one who is showed in AAD and audit logs.
The issue will be fixed on Q4 of this year.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103da6d9-ae2b-dea2-053d-922600686950
* Version Independent ID: 62501206-4fee-8016-bff1-309eae334d75
* Content: [Information about Teams known issues - Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/troubleshoot/teams-welcome)
* Content Source: [Teams/teams-welcome.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Teams/teams-welcome.md)
* Service: **msteams**
* GitHub Login: @AmandaAZ
* Microsoft Alias: **v-weizhu**

**Comment by nam31** [comment]
@Yuhan-Meng The best way to get your issue resolved is to contact Microsoft Support. 
If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 
Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
