### ISSUE TITLE
access activation URLs w/ proxy authentication

### ISSUE THREAD

**Issue by sigurd-de** [MicrosoftDocs/OfficeDocs-Support#891]
if a company is using proxy authentication it is critical to see if the URIs are used in the user context or if it is the machine account that needs to access the URIs

Can you please add this specification to the documentation?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42bf62b-d9cb-d9c6-5528-a641971b24eb
* Version Independent ID: e50b41e9-6c2f-f02d-e45f-b52f08076f1a
* Content: [Cannot connect to your account when activate Office from Office 365 - Office](https://docs.microsoft.com/en-us/office/troubleshoot/activation/issue-when-activate-office-from-office-365#step-3-check-whether-youre-behind-a-firewall)
* Content Source: [Office/Client/activation/issue-when-activate-office-from-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/activation/issue-when-activate-office-from-office-365.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@sigurd-de Thank you for your feedback. Sorry about the delay in answering your query.  winhttp proxy settings are always machine-specific and the registry key to access it and add a bypass list would be HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections\WinHttpSettings 

Since this is by design I don't think this specification can be added to the document.

Hope this helps!

Thanks
Sri

**Comment by nam31** [comment]
@sigurd-de Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
