### ISSUE TITLE
Blank can also occur for other attributes

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Support#905]
From the page:

> When you run the IdFix DirSync Error Remediation Tool in your on-premises Active Directory Domain Services (AD DS) environment, "blank" is displayed in the ERROR column for one or more objects.
> This occurs if the displayName attribute of the object isn't defined.

However, you can get a "Blank" error for other attributes - eg TargetAdress seems common. 
In that case, it seems only relevant for remote mailboxes and can be ignored for local (I think?) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db566fd4-4367-a988-344c-aea1634dbe0a
* Version Independent ID: ab81c32e-dcdd-8333-62c0-7886726c184b
* Content: [Blank is displayed in the ERROR column for one or more objects - Office 365](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/idfix-not-display-objects-errors)
* Content Source: [Microsoft365/admin/active-directory/idfix-not-display-objects-errors.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Microsoft365/admin/active-directory/idfix-not-display-objects-errors.md)
* Product: **office 365**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@GLComputing Thank you for your feedback. If a blank Datagrid is displayed after execution, then no errors were returned. This is a good thing and that is what happens when it shows for other attributes like Target address. However, when a Blank error comes up it is primarily on the display name attribute as the Value violates the null restriction for the attribute to be synchronized. This document primarily focuses on that.

Hope this helps!

Thanks
Sri

**Comment by GLComputing** [comment]
The issue is that a search will find this article, but the solution doesn't apply to TargetAddress.
Can those be ignored or do they need a fix before moving up to 365?

**Comment by msbemba** [comment]
@GLComputing Good question. Ideally, the Target address is updated only after the Migration is complete. i.e when the mailbox is in the cloud and on-prem needs a target/remote routing address to the route. So it can be ignored.

Thanks
Sri

**Comment by nam31** [comment]
@GLComputing Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
