### ISSUE TITLE
The article doesn't confirm if the issue ocurs with user mailbox only or also with shared mailbox as well

### ISSUE THREAD

**Issue by ldusolier** [MicrosoftDocs/OfficeDocs-Support#915]
https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-on-the-web-issues/incorrect-setting

The article doesn't confirm if the issue occurs with user mailbox only or also with shared mailbox as well
Can this be added to the article to remove doubts?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f6624f-b839-c29e-8c4a-53f9c51e7c80
* Version Independent ID: 579ede46-f6e6-d237-1088-48c26ebfa852
* Content: [The time zone setting is set incorrectly to (UTC) Monrovia, Reykjavik - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-on-the-web-issues/incorrect-setting#feedback)
* Content Source: [Exchange/ExchangeOnline/outlook-on-the-web-issues/incorrect-setting.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-on-the-web-issues/incorrect-setting.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@ldusolier  Thank you for your feedback. This article pertains to a shared mailbox as it is not assigned a license by default or immediately after creating it. The Time zone setting on a mailbox is set when the user logs in to the mailbox via outlook web access. So a time zone isn't automatically set after a shared mailbox is created because users don't sign in to shared mailboxes directly.

Hope this helps!
Thanks
Sri

**Comment by nam31** [comment]
@ldusolier Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
