### ISSUE TITLE
Instructions have Windows Remediation for a MacOS Page

### ISSUE THREAD

**Issue by malokam** [MicrosoftDocs/OfficeDocs-Support#961]
Instructions have Windows Remediation for a MacOS Page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b5732-ef8a-f040-4cde-d9fc40486764
* Version Independent ID: 053a2e2a-d7a1-2562-8d83-b65263c6ec92
* Content: [Email messages are stuck in Outbox in Outlook 2016 for Mac - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac)
* Content Source: [Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/send-receive-emails/email-stuck-in-outbox-outlook-2016-mac.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by MaratMussabekov** [comment]
Hello, it is not a mistake.
To fix this issue on MacOS, you may need to reset folders in the mailbox using the Outlook on Windows machine.
Thank you

**Comment by nam31** [comment]
@malokam Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
