### ISSUE TITLE
Workaround for hanged Outlook

### ISSUE THREAD

**Issue by bostjanlaba** [MicrosoftDocs/OfficeDocs-Support#995]
Workaround: 

create a batch file KillOutlook.cmd with contents:
`taskkill /F /IM outlook.exe /T`
`start "" "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"`

Now point your outlook shortcut to this cmd file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed455468-b15e-1e87-c542-8cb97ebc327f
* Version Independent ID: e51cb47b-8b93-b0f2-09e2-5dca1435b951
* Content: [Outlook crash or stop responding when used with Office 365 - Exchange](https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-issues/crash-issues)
* Content Source: [Exchange/ExchangeOnline/outlook-issues/crash-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Exchange/ExchangeOnline/outlook-issues/crash-issues.md)
* Service: **exchange-online**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@bostjanlaba Thank you for your feedback. The cmd's and the batch file did work (kill and start the process). However adding that would confuse the general audience. Moreover, We have step 5 which explains the usage of the SARA tool which does Force kill the Process before the customer contacts Support for help.

Thanks again for the workaround, 

@nam31 There are no changes need in the document and the issue can be closed.

Thanks
Sri

**Comment by nam31** [comment]
@bostjanlaba Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by bostjanlaba** [comment]
I'm using a workaround all this time. However, some of our PCs in the company still experience this exact problem on daily basis.

**Comment by msbemba** [comment]
@bostjanlaba Thank you for your feedback. Are all those machines and office suites Up to date? What happens when you follow the 5 steps provided in the document?

Thanks
Sri

**Comment by bostjanlaba** [comment]
4 steps didn't help much. I just tried SaRa step which disabled hw acceleration and it seems fine now. I'll test these machines for a day or two and report back if the issue has been resolved.

Thank you.

**Comment by msbemba** [comment]
@bostjanlaba The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Thanks
Sri
